

export enum DeltaType {
    ADD_TILE_CONTENT = "ADD_TILE_CONTENT",
    REMOVE_TILE_CONTENT = "REMOVE_TILE_CONTENT",
    ROTATE_HAMSTER = "ROTATE_HAMSTER",
    ADD_LOG_ENTRY = "ADD_LOG_ENTRY",
    REMOVE_LOG_ENTRY = "REMOVE_LOG_ENTRY",
    NEW_TERRITORY = "NEW_TERRITORY"
}